services:
  kronoterm_cloud_relay:
    image: leskoiam/kronoterm_cloud_relay:latest
    container_name: kronoterm_cloud_relay
    restart: unless-stopped
    ports:
      - "8555:8555"  # Adjust the port mappings as needed
    environment:
      # Add your kronoterm cloud username and password
      - KRONOTERM_CLOUD_USER="your-user"
      - KRONOTERM_CLOUD_PASSWORD="your-password"

