version: '3.8'

services:
  kronoterm_cloud_relay:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8555:8555"
    environment:
      - FLASK_APP=src/kronoterm_cloud_relay.py
    command: flask run --host=0.0.0.0 --port=8555
