services:
  kronoterm_cloud_relay:
    image: leskoiam/kronoterm_cloud_relay:latest
    container_name: kronoterm_cloud_relay
    restart: unless-stopped
    ports:
      - "8555:8555"  # Adjust the port mappings as needed
    ## If you are having problems with slow connection uncomment lines bellow.
    ## GitHub issue reference [#26](https://github.com/LeskoIam/kronoterm_cloud_relay/issues/26)
    # extra_hosts:
    #   - "cloud.kronoterm.com=145.14.48.71"  # TODO: don't forget to periodically check the validity of IP
    environment:
      # Add your kronoterm cloud username and password
      - KRONOTERM_CLOUD_USER="your-user"
      - KRONOTERM_CLOUD_PASSWORD="your-password"

